Allow manual job expiration.
VEuPathDB/lib-compute-platform pull request #37
Opened 2023-03-08 14:47 UTC by Foxcapades

### Description
Job expiration method.

### Changes
- Adds a method to AsyncPlatform that allows for the manual expiration of individual jobs.

### PR Checklist
* [x] Updated relevant source docs
* [x] Updated readme / docs
* [x] Updated dependencies

2023-03-08 18:37 UTC, ryanrdoherty requested changes

2023-03-08 18:37 UTC, ryanrdoherty commented on lib/src/main/kotlin/org/veupathdb/lib/compute/platform/AsyncPlatform.kt
> +      .finished ?: throw IllegalStateException("Attempted to incomplete job $jobID")
Attempted **to expire** incomplete job X

2023-03-08 18:37 UTC, ryanrdoherty commented on lib/src/main/kotlin/org/veupathdb/lib/compute/platform/AsyncPlatform.kt
> +      ?: throw IllegalStateException("Attempted to expire unowned job $jobID"))
I feel like it would be nice to know which of these cases it is.  Can you either use separate exceptions, a custom exception with a status/reason, or a return code to indicate what happened?  I'm considering adding a background thread that keeps trying at these until they are all finished.  That would be necessary here if we really want to make sure running jobs are also expired, yes?

2023-03-08 18:55 UTC, Foxcapades commented on lib/src/main/kotlin/org/veupathdb/lib/compute/platform/AsyncPlatform.kt
> +      ?: throw IllegalStateException("Attempted to expire unowned job $jobID"))
Now throws separate exceptions for the 2 separate cases.

2023-03-10 15:28 UTC, ryanrdoherty approved these changes

2023-03-10 15:32 UTC, merged